/**
 * 定义应用路由
 */
import React from 'react';
import {
  Router,
  // browserHistory,
  hashHistory,
} from 'react-router';

// 以下部分是由 ICE 相关工具自动生成的路由，请勿随意改变，否则可能会出现一些异常情况
// <!-- auto generated routes start -->
import HeaderAsideFooterResponsiveLayout from './layouts/HeaderAsideFooterResponsiveLayout';
import Dashboard from './pages/Dashboard';
import Charts from './pages/Charts';
import Portlets from './pages/Portlets';
import Terms from './pages/Terms';
import ProgressInfo from './pages/ProgressInfo';
import Result from './pages/Result';
import HeaderAsideFooterLayout from './layouts/HeaderAsideFooterLayout';
import Fail from './pages/Fail';
import FixedHeaderFooterResponsiveLayout from './layouts/FixedHeaderFooterResponsiveLayout';
import Landing from './pages/Landing';
import ServerError from './pages/ServerError';
import Forbidden from './pages/Forbidden';
import EmptyContent from './pages/EmptyContent';
import List from './pages/List';
import CardList from './pages/CardList';
import PicturesList from './pages/PicturesList';
import BasicTable from './pages/BasicTable';
import TableList from './pages/TableList';
import TableDisplay from './pages/TableDisplay';
import NotFound from './pages/NotFound';
import Page21 from './pages/Page21';
import HeaderFooterLayout from './layouts/HeaderFooterLayout';
import Page23 from './pages/Page23';
import Page24 from './pages/Page24';
const autoGeneratedRoutes = [
  {
    path: '/list',
    childRoutes: [
      { path: 'article-list', childRoutes: [], component: List },
      { path: 'card-list', childRoutes: [], component: CardList },
      {
        path: 'picture-list',
        childRoutes: [],
        component: PicturesList,
      },
    ],
    component: HeaderAsideFooterLayout,
    indexRoute: { component: List },
  },
  {
    path: '/page24',
    childRoutes: [],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: { component: Page24 },
  },
  {
    path: '/table',
    childRoutes: [
      {
        path: 'basic-table',
        childRoutes: [],
        component: BasicTable,
      },
      {
        path: 'table-list',
        childRoutes: [],
        component: TableList,
      },
      {
        path: 'table-display',
        childRoutes: [],
        component: TableDisplay,
      },
    ],
    component: HeaderAsideFooterLayout,
    indexRoute: { component: BasicTable },
  },
  {
    path: '/portlets',
    childRoutes: [
      { path: 'base', childRoutes: [], component: Portlets },
      { path: 'terms', childRoutes: [], component: Terms },
      {
        path: 'progress',
        childRoutes: [],
        component: ProgressInfo,
      },
    ],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: { component: Portlets },
  },
  {
    path: '/page23',
    childRoutes: [],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: { component: Page23 },
  },

  {
    path: '/page21',
    childRoutes: [],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: { component: Page21 },
  },


  {
    path: '/result',
    childRoutes: [
      { path: 'success', childRoutes: [], component: Result },
      { path: 'fail', childRoutes: [], component: Fail },
    ],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: { component: Result },
  },
  {
    path: '/chart',
    childRoutes: [{ path: 'chart-list', childRoutes: [], component: Charts }],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: { component: Charts },
  },
  {
    path: '/exception',
    childRoutes: [
      { path: '500', childRoutes: [], component: ServerError },
      { path: '403', childRoutes: [], component: Forbidden },
      { path: '204', childRoutes: [], component: EmptyContent },
      { path: '404', childRoutes: [], component: NotFound },
    ],
    component: HeaderAsideFooterLayout,
    indexRoute: { component: ServerError },
  },
  {
    path: '/landing',
    childRoutes: [],
    component: FixedHeaderFooterResponsiveLayout,
    indexRoute: { component: Landing },
  },
  {
    path: '/',
    childRoutes: [],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: { component: Dashboard },
  },
];

// <!-- auto generated routes end -->

// 自定义路由，如果 path 相同则会覆盖自动生成部分的路由配置
const customRoutes = [];

export default (
  <Router
    history={hashHistory}
    routes={[...autoGeneratedRoutes, ...customRoutes]}
  />
);
